### ISSUE TITLE
I can see Passed Tests only in Test List

### ISSUE THREAD

**Issue by xcyroo** [GHPReporter/Ghpr.Core#14] opened 2016-11-10 10:33 UTC
![ghprtestlist](https://cloud.githubusercontent.com/assets/13576204/20173420/88c09102-a739-11e6-9a84-ddf5314ca24a.png)

**Comment by elv1s42** [comment] 2016-11-10 11:51
Hello! Thanks for this issue.

Can you please provide more information about it?
Are you using NUnit, MSTest or SpecFlow plugin?

Can you see some "Exception_*.txt" files inside GHPR output folder? If so, please attachthem to this issue, or just copy and paste StackTrace here.

Do you have "TakeScreenshotAfterFail" enabled? If so, this issue can be related with https://github.com/GHPReporter/Ghpr.NUnit/issues/7

**Comment by xcyroo** [comment] 2016-11-10 12:04
I am using NUnit and I can see several exceptions in report folder. Test list is the only place where FAILED TCs are missing.  Following Exceptions alternate in report folder:

Exception in method '<TestFinished>b__0'
 Message: 
The handle is invalid
StackTrace: 
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   at Ghpr.Core.Utils.Taker.TakeScreenshot(String screenPath, DateTime creationTime)
   at Ghpr.Core.Extensions.TestRunExtensions.TakeScreenshot(ITestRun testRun, String testPath, Boolean takeScreenshotAfterFail)
   at Ghpr.Core.Reporter.<>c__DisplayClass26_0.<TestFinished>b__0()
   at Ghpr.Core.Utils.ActionHelper.SafeAction(Action a)


Exception in method '<GenerateReport>b__0'
 Message: 
Collection was modified; enumeration operation may not execute.
StackTrace: 
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Ghpr.Core.Helpers.ItemInfoHelper.SaveItemInfo(String path, String filename, ItemInfo itemInfo, Boolean removeExisting)
   at Ghpr.Core.Reporter.<>c__DisplayClass21_0.<GenerateReport>b__0()
   at Ghpr.Core.Utils.ActionHelper.SafeAction(Action a)

**Comment by elv1s42** [comment] 2016-11-10 12:26
Good!

The first exception is about taking screenshot. @xcyroo, are you using Jenkins to run NUnit tests?

The second one looks strange. Are you using the latest version of Ghpr.Core and Ghpr.NUnit?

**Comment by xcyroo** [comment] 2016-11-10 13:31
I am using Bamboo agent to execute test using nunit3 console. And yes, I have latest versions.

**Comment by elv1s42** [comment] 2016-11-10 13:41
Ok. For the first exception I will try to provide another way of taking screenshots. I think this is the same problem as https://github.com/GHPReporter/Ghpr.NUnit/issues/7
Please let me know, if you are using Selenium WebDriver.

For the second exception please try to use **--agents=1** inside NUnit Console command

**Comment by xcyroo** [comment] 2016-11-10 13:52
Yes, I am using Selenium WebDriver. I am getting the same exception when running with --agents=1 --workers=1 :/

**Comment by xcyroo** [comment] 2016-11-29 20:16
any idea how to solve this issue? I can still see passed TCs only.

**Comment by elv1s42** [comment] 2016-11-30 08:12
Hello again. 
The work is still in progress, but you can try to switch `TakeScreenshotAfterFail` to `False`. This should resolve issue with taking screenshots. The issue is in taking screenshots, for now it works only on local PC

**Comment by xcyroo** [comment] 2016-11-30 12:20
I also noticed that I am getting http 404 when requesting tablesort.min.js and jquery-1.11.0.min.js. Those files are not included in report output. Is this connected to this issue?

**Comment by elv1s42** [comment] 2016-11-30 15:31
No, this is not the reason of this issue. Please, try `TakeScreenshotAfterFail` and let me know if it works or not

**Comment by kharod** [comment] 2017-01-10 03:05
Heya,

I think, I am having same Issue. I am getting Exception:
Exception in method '<TestFinished>b__0'
 Message: 
The handle is invalid
StackTrace: 
   at System.Drawing.Graphics.CopyFromScreen(Int32 sourceX, Int32 sourceY, Int32 destinationX, Int32 destinationY, Size blockRegionSize, CopyPixelOperation copyPixelOperation)
   at Ghpr.Core.Utils.Taker.TakeScreenshot(String screenPath, DateTime creationTime)
   at Ghpr.Core.Extensions.TestRunExtensions.TakeScreenshot(ITestRun testRun, String screenPath, Boolean takeScreenshotAfterFail)
   at Ghpr.Core.Reporter.<>c__DisplayClass41_0.<TestFinished>b__0()
   at Ghpr.Core.Utils.ActionHelper.SafeAction(Action a)

I am running the Tests from Teamcity, using Nunit and Selenium Webdriver and Grid to run the tests.
Any idea when this will be fixed, as it is more important to see the Failed tests in report and the screenshots at failure?

Thanks in advance.

**Comment by elv1s42** [comment] 2017-01-10 09:32
Hi @kharod !
For now taking screenshots may not work for some CI tools (like TeamCity or Jenkins).

You can take a look at this way of taking screenshots (some kind of workaround for this issue): https://github.com/GHPReporter/Ghpr.NUnit.Examples/blob/master/Ghpr.NUnitTests/TestingScreenshotTaking.cs

**Comment by kharod** [comment] 2017-01-10 23:01
Heya @elv1s42 

Thanks for the reply.
I am going to try this workaround.

Are you going to fix that Failed Tests are not showing up in the report?

Thanks.

**Comment by elv1s42** [comment] 2017-01-11 09:05
> Are you going to fix that Failed Tests are not showing up in the report?

This issue is connected with taking screenshots. 
Are you using the latest version?

**Comment by elv1s42** [comment] 2017-01-17 15:11
Hi @xcyroo and @kharod 
Please let me know if this issue has gone with latest Ghpr.Core, Ghpr.NUnit (both v0.4.3) and NUnit.Console (v3.6).

**Comment by elv1s42** [comment] 2017-01-17 16:08
If you are going to take screenshots inside yout tests, then make sure that you have the same `Ghpr.NUnit.Settings.json` file inside your C# project and inside NUnit.Console addins folder.

Also, take a look at [How to work with screenshots section.](https://github.com/GHPReporter/Ghpr.NUnit#how-to-work-with-screenshots)

**Comment by xcyroo** [comment] 2017-01-18 14:02
I just found out that when I execute test using nunit console, I can see failed TCs in UI but when the tests are triggered by my CI tool (bamboo) - the same command for nunit console, just Passed TCs are visible...

**Comment by elv1s42** [comment] 2017-01-18 16:10
@xcyroo are you using the latest version of Ghpr.Core and Ghpr.NUnit?

**Comment by xcyroo** [comment] 2017-02-08 10:00
HI, I am using the latest right now but still I can see just passed TCs :/

**Comment by elv1s42** [comment] 2017-02-08 10:06
I need some data to work with. 
Can you see .json files for failed tests inside report folder?
Are there any errors in browser console and what browser are you using?
Can you send me the whole report?

**Comment by xcyroo** [comment] 2017-02-08 10:16
[identitymanagement.zip](https://github.com/GHPReporter/Ghpr.Core/files/760286/identitymanagement.zip)

see the report. Those tests are just hitting REST API so they do not use webdriver and browser.
Thanks

**Comment by elv1s42** [comment] 2017-02-08 13:03
@xcyroo can you please try this one:
[Ghpr.Core.zip](https://github.com/GHPReporter/Ghpr.Core/files/760654/Ghpr.Core.zip)

**Comment by xcyroo** [comment] 2017-02-08 13:18
still not working
[_GhprReport.zip](https://github.com/GHPReporter/Ghpr.Core/files/760687/_GhprReport.zip)

**Comment by elv1s42** [comment] 2017-02-08 14:36
@xcyroo I think you are using not the latest version of Ghpr.Core, please take a look at [usage instructions](https://github.com/GHPReporter/Ghpr.NUnit#usage). It is not ehough to update NuGet package, you need to put all files into nunit3-console addins folder, because generally speaking Ghpr.NUnit is extension for nunit-console.

I've took ghpr.controller.js file from your report and compared it with the latest one (see screenshot attached). They are not the same, which means that Ghpr.Core version is not the latest.
![2017-02-08 17_24_34-computed diff - diff checker](https://cloud.githubusercontent.com/assets/6689884/22741274/a997d576-ee23-11e6-8b82-a7eedd9927af.png)

**Comment by xcyroo** [comment] 2017-02-09 08:40
I will try to install nunit-console with all addins in different machine by following usage instructions and let you know results.

**Comment by elv1s42** [comment] 2017-02-09 08:47
Good, thank you. Please try using Ghpr.Core 0.4.4 and Ghpr.NUnit 0.4.4.

**Comment by xcyroo** [comment] 2017-02-09 09:39
[_GhprReport.zip](https://github.com/GHPReporter/Ghpr.Core/files/763202/_GhprReport.zip)
still not working for me :/

it just work when I execute tests manually. When the execution is triggered from bamboo the issue persists.

**Comment by elv1s42** [comment] 2017-02-09 10:32
Still I'm not sure that this is the latest report.
I've updated years for report pages: https://github.com/GHPReporter/Ghpr.Core/commit/5bfa64e042cce6ff7b36ad2980c494a43bb34b60

New reports will contain 2017 year. 

And also ghpr.controller.js file looks not like the latest one. 

Can you try to generate report to new folder and make sure that Bamboo uses the latest versions of Ghpr and NUnit Console?

**Comment by xcyroo** [comment] 2017-02-09 12:14
Ok, I got it. Issue was on my side and Bamboo still called nunit-console from obsolete folder.
Sorry for confusion. Now it looks that everything just works fine.

Thanks for the support.

**Comment by elv1s42** [comment] 2017-02-09 12:46
Good to know!
Thanks for the update, I am closing this one.

I will create an issue about adding Core version number somwhere on the report page, just to make sure that in the next releases new report will contain information about Core library version. In that case we won't need to spend much time on investigating which Core version produced the report.

**Closed by elv1s42** 2017-02-09 12:46 UTC

**Comment by elv1s42** [comment] 2017-02-09 12:47
#26 created
