### ISSUE TITLE
dynamic output path

### ISSUE THREAD

**Issue by dddkiran** [GHPReporter/Ghpr.Core#63] opened 2018-06-11 08:04 UTC
Hey!

We have one diagnostics project for monitoring different products(web1/web2..) in different environments (qa/test/beta). 

Is it possible to pass Ghpr.NUnit.Settings.json or output path dynamically though nunit parameters ?

Cherrs,
Kiran

**Comment by elv1s42** [comment] 2018-06-11 12:18
Hi @dddkiran,
I had a similar idea more than a year ago and raised an issue in NUnit repository:
https://github.com/nunit/nunit-console/issues/148

The idea was to be able to pass Ghpr settings via NUnit Console command line arguments.

The issue is not resolved at the moment, so I can suggest using some workaround like for example running `.ps1` script (which will change `.json` settings file) as a separate step of your CI process before executing tests.

**Comment by elv1s42** [comment] 2018-07-06 14:21
Closing for now as there is no way to extract arguments from NUnit Console arguments at the moment, and there is a workaround like for example running `.ps1` script (which will change `.json` settings file) as a separate step of your CI process before executing tests.

**Closed by elv1s42** 2018-07-06 14:21 UTC
Labels: ghpr-core, ghpr-nunit, question

**Comment by elv1s42** [comment] 2019-07-08 10:58
Hi @dddkiran ,

Ghpr.Core now supports mulitple project settings in one config file: https://github.com/GHPReporter/Ghpr.Core#about-settings-file

Thank you
