### ISSUE TITLE
Getting could not load Ghpr.Core assembly error while running nunit3-console

### ISSUE THREAD

**Issue by Nabakamal** [GHPReporter/Ghpr.Core#123] opened 2019-08-08 10:45 UTC
Running nunit3-console.exe "My.dll" gives me this error: 
**Could not load file or assembly 'Ghpr.Core, Version=0.9.9.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.**

Steps to reproduce this behaviour:
1. Running nunit3-console.exe "My.dll" from this location  {My}\packages\NUnit.ConsoleRunner.3.10.0\tools\ gives me this error. 

Here is how my packages.config file looks like:
![image](https://user-images.githubusercontent.com/22019429/62696769-b9b12b00-b9f6-11e9-9592-14c9782d0188.png)

**Expected behavior**
The command should execute and my tests should be run. It is a VS2017 unit test project containing 2 simple Selenium tests.

**Screenshots**
![image](https://user-images.githubusercontent.com/22019429/62697000-4eb42400-b9f7-11e9-9e51-6da646f76ca9.png)

**Desktop (please complete the following information):**
 - Browser: Chrome 75.something
 - Ghpr packages versions : Ghpr.Core v0.9.9.1, Ghpr.NUnit v0.9.9.1

**Comment by elv1s42** [comment] 2019-08-12 14:18
Hi @Nabakamal !

Thank you for the issue.

Most likely you need to change corresponding `.addins` file for NUnit to start seeing the extension. Please usage section for more details: https://github.com/GHPReporter/Ghpr.NUnit#usage

**Comment by Nabakamal** [comment] 2019-08-19 05:25
Hi, sorry for the delayed response. I was on a vacation. My .addins file (..\packages\NUnit.ConsoleRunner.3.10.0\tools\nunit.nuget.addins) looks like this:

../../NUnit.Extension.*/**/tools/        # nuget v2 layout
../../../NUnit.Extension.*/**/tools/     
../../../../NUnit.Extension.*/**/tools/  # nuget v3 layout
../../Ghpr.Core.0.9.9.1/lib/net452/Ghpr.Core.dll
../../Ghpr.NUnit.0.9.9.1/lib/net452/Ghpr.NUnit.dll

In spite of this, I get the errors I mentioned above. Please assist.

**Comment by elv1s42** [comment] 2019-08-20 11:00
Hi @Nabakamal !
I was able to reproduce the issue using [NUnit.Examples](https://github.com/GHPReporter/Ghpr.NUnit.Examples) repository.

When the `.addins` file is configured like this: 
![image](https://user-images.githubusercontent.com/6689884/63341421-dbdd6e00-c351-11e9-9902-c1459e09aeb0.png)

there is an error: 
![image](https://user-images.githubusercontent.com/6689884/63341456-ec8de400-c351-11e9-88a3-1e70da054e66.png)

The fix is to use the path to Ghpr.NUnit file from your build folder (`bin/Debug` by default).
In my case it was: 
![image](https://user-images.githubusercontent.com/6689884/63341567-2c54cb80-c352-11e9-836f-3db215ded6f9.png)

The run was successful after that:
![image](https://user-images.githubusercontent.com/6689884/63341594-3d9dd800-c352-11e9-8dd3-df4804753e34.png)

I also raised an issue to fix it in the future: https://github.com/GHPReporter/Ghpr.NUnit/issues/57
In general we should not do any modifications to `.addins` file after the issue is resolved.

Thank you.

**Comment by Nabakamal** [comment] 2019-08-20 11:11
Hi! Thank you for that fix...now, however, after making that change, I get this(may not be related to this issue):

![image](https://user-images.githubusercontent.com/22019429/63342431-1dc5de80-c369-11e9-9fb4-a1009e8465cc.png)

Do you know what may be causing this? I am using this format:
>nunit3-console.exe "C:\Path-to-my-DLL\My.dll"

**Comment by Nabakamal** [comment] 2019-08-20 11:19
My bad! Sorry. I had added an absolute path in the .addins file to the Ghpr.Nunit.dll. When I modified it to have a relative path (with a lot of ..s), the issue isn't coming up anymore. Thanks.

**Comment by elv1s42** [comment] 2019-08-20 11:28
Thank you for confirming that the issue is fixed for you!

According to [NUnit documentation](https://github.com/nunit/docs/wiki/Engine-Extensibility#locating-addins):

> Wildcards may be used for assembly entries and relative paths are interpreted based on the location of the .addins file

So it looks like NUnit supports only relative paths, that's why you were getting an error.

Closing the issue.

**Closed by elv1s42** 2019-08-20 11:28 UTC
Labels: question
